# fly.toml app configuration file generated for club-lime-classes on 2025-02-15T09:45:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'club-lime-classes'
primary_region = 'syd'

[build]
[build.args]
GO_VERSION = '1.24'x

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
